package test.java.controlBola;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;

import controlBola.Principal;

/**
 * {@link Principal} specific assertions - Generated by CustomAssertionGenerator.
 */
public class PrincipalAssert extends AbstractAssert<PrincipalAssert, Principal> {

	/**
	 * Creates a new </code>{@link PrincipalAssert}</code> to make assertions on actual Principal.
	 * @param actual the Principal we want to make assertions on.
	 */
	public PrincipalAssert(Principal actual) {
		super(actual, PrincipalAssert.class);
	}

	/**
	 * An entry point for PrincipalAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
	 * With a static import, one's can write directly : <code>assertThat(myPrincipal)</code> and get specific assertion with code completion.
	 * @param actual the Principal we want to make assertions on.
	 * @return a new </code>{@link PrincipalAssert}</code>
	 */
	public static PrincipalAssert assertThat(Principal actual) {
		return new PrincipalAssert(actual);
	}

}
